### PR TITLE
I do this to everyone haha

### PR DESCRIPTION
**Pull request by MajikalPayton**

### CODE REVIEW

**Comment by TahaTheHacker** [comment]
oops, LOL this plugin is just private xD.

**Comment by MajikalPayton** [comment]
No problem! If I were here to develop the plugin for you, I'd probably change it all haha! Kidding. I'll be happy to help, no matter what the problem is.

**Comment by TahaTheHacker** [comment]
@MajikalPayton :+1: there is no need :smile: 
Thanks

**Comment by MajikalPayton** [comment]
Also, I recommend you stay consistent with style :) I'll submit a PR that cleans stuff up a bit.

**Comment by TahaTheHacker** [comment]
:1+: But we're spamming other's notifications..

**Comment by MajikalPayton** [comment]
You're spamming two other's notifications. :P

**Pull request merged**
